# Generated by Django 4.2.7 on 2023-11-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genres',
            name='tmdb_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
