# Generated by Django 4.2.7 on 2023-11-21 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviegenre',
            old_name='genres',
            new_name='genre',
        ),
    ]
