# Generated by Django 4.2.7 on 2023-11-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
